version: '3.8'

#volumes:
  #aml-bet_data:
services:
  aml-bet_db:
    image: nategauvin/aml-bet_db:latest
    restart: always
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    #volumes:
      #- aml-bet_data:/data/db

#  mongo-express:
#    image: mongo-express:0.54.0 
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  aml-bet:
    image: nategauvin/aml-bet_shiny:latest
    restart: always
    ports:
        - 3838:3838
    environment:
        MONGO_HOST: mongo
    links:
        - aml-bet_db