name: process_upload

on:
  push:
    paths:
      - functions/*.R
      - .github/workflows/process_upload.yml

jobs:
  test-process:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: database
        ports:
          - 27017:27017
    
    steps:
      - name: set up R
        uses: r-lib/actions/setup-r@v2

      - name: install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::ggplot2
            any::tidyverse
            any::MASS
            any::mongolite
            any::argparse

      - name: add repo
        uses: actions/checkout@v3

      - name: install mongosh for initialization
        run: |
          sudo apt-get install gnupg
          wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          mongosh --version

      - name: initialize mongodb
        run: |
          mongosh --host localhost:27017 -u root -p password --authenticationDatabase admin <<EOF
            db = db.getSiblingDB('database');
            db.createUser({ user: 'admin', pwd: 'password', roles: [{ role: 'readWrite', db: 'database' }] })
            db.createCollection('aml-bet');
          EOF

      - name: process all datasets with upload
        run: Rscript functions/commandLineParser.R --db yes
