name: process_upload

on:
  push:
    paths:
      - functions/*.R
      - .github/workflows/process_upload.yml

jobs:
  test-process:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
    
    steps:
      - name: set up R
        uses: r-lib/actions/setup-r@v2

      - name: install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::ggplot2
            any::tidyverse
            any::MASS
            any::mongolite
            any::argparse

      - name: add repo
        uses: actions/checkout@v3

      - name: process all datasets with upload
        run: Rscript functions/commandLineParser.R --db yes
